# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc7d61d40420f12a7f73368c687f010bed2f2a4af6989f4a415bcee6fb688b5446f586cc265e1140a30db84b5b4e445a3415dc6cb3689e1c120db1681eb31092

test:
  secret_key_base: c4bf4189473a2203d9de6814048fae129b4d04edac86442deb59b0fbeed8a1f30c62018beb461c7fee58d639b81601e97edb0b2938db10cb5edf43d0cfbc938a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
